---
name: Checks

permissions: read-all

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    name: Isort
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          format: black

  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  type_check:
    runs-on: ubuntu-latest
    container: candidj0/milo:base

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get Python version
        id: python_version
        run: |
          python_version="$(python --version 2>&1 | awk '{print $2}')"
          echo PYTHON_VERSION="$python_version" >> "$GITHUB_ENV"

      - name: Get Poetry version
        id: poetry_version
        run: |
          poetry_version="$(poetry --version | cut -d' ' -f3 | sed 's/[()]//g')"
          echo POETRY_VERSION="$poetry_version" >> "$GITHUB_ENV"

      - name: Cache Poetry cache
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{
            env.PYTHON_VERSION }}-${{
            env.POETRY_VERSION }}

      - name: Cache Packages
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{
            env.PYTHON_VERSION }}-${{
            hashFiles('**/poetry.lock') }}-${{
            hashFiles('.github/workflows/*.yml') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run type-check
        run: poetry run poe type-check
