---
name: Checks

permissions: read-all

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    name: Isort
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          format: black

  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  type_check:
    runs-on: ubuntu-latest
    container: candidj0/milo:base

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: poetry run pip install mypy

      - name: Run type-check
        run: poetry run poe type-check
