---
name: Checks

permissions: read-all

on:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    name: Isort
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          format: black

  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  type_check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install poetry
      - run: poetry run pip install poethepoet mypy
      - run: poetry run poe type_check
