---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          RUN_LOCAL: ${{ env.ACT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          FILTER_REGEX_EXCLUDE: .*/data/*
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_ISORT: false
