---
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request: null

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    container: candidj0/milo:base

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Python version
        id: python_version
        run: |
          python_version="$(python --version 2>&1 | awk '{print "$2"}')"
          echo PYTHON_VERSION="$python_version" >> "$GITHUB_ENV"

      - name: Get Poetry version
        id: poetry_version
        run: |
          poetry_version="$(poetry --version | cut -d' ' -f3)"
          echo POETRY_VERSION="$poetry_version" >> "$GITHUB_ENV"

      - name: Cache Poetry cache
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{
            env.PYTHON_VERSION }}-${{
            env.POETRY_VERSION }}

      - name: Cache Packages
        if: ${{ !env.ACT }}
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-local-${{ runner.os }}-${{
            env.PYTHON_VERSION }}-${{
            hashFiles('**/poetry.lock') }}-${{
            hashFiles('.github/workflows/*.yml') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint code
        run: poetry run flake8 .

      - name: Format code
        run: poetry run black --check --diff .

      - name: Run tests
        run: poetry run python -m pytest
